### ISSUE TITLE
How should I configure the udp port?

### ISSUE THREAD

**Issue by wookjin** [Xinyu-Yi/PIP#23]
![스크린샷 2023-05-09 233649](https://github.com/Xinyu-Yi/PIP/assets/30368065/14621955-9e90-4427-ab66-b21c8ef23a96)

I have an older version of the perception neuron sensor. 

First of all, I tried to test it with all the sensors worn. 

I set the udp port as in the attached image. 

However, the error written in the second attached image occurred.

![스크린샷 2023-05-09 233957](https://github.com/Xinyu-Yi/PIP/assets/30368065/1c5a6755-1f60-44d5-a470-6eb951490c77)

**Comment by Xinyu-Yi** [comment]
I think the api I used (https://github.com/pnmocap/MocapApi) does not support your software. Maybe you can check the api website (it seems that it only supports "Axis Studio"). From the first picture, it seems that you can directly write a client and receive the string-format inertia measurements, i.e., you can parse the string by yourself instead of using the api?

**Comment by wookjin** [comment]
After posting the question, the sensor of the perception neuron in the laboratory was stolen. I am trying motion sensing by purchasing a low-cost imu sensor. If you want to give this project a try, can you just enter the values ​​for the individual sensors listed below?

quaternion w,x,y,z

acceleration x, y, z

Should I initialize the sensor value with t-pose and then input it?

**Comment by Xinyu-Yi** [comment]
Sorry, I did not understand what you mean.

**Comment by wookjin** [comment]
In which order should I put the data: head, left foot, right foot, left arm, right arm? Does the order of input data matter?
